<testsuites>
  <testsuite name="JUnit.Xml.TestLogger.NetCore.Tests.dll" tests="52" skipped="6" failures="14" errors="0" time="0.87068" timestamp="2021-04-04T16:42:06" hostname="REDACTED" id="0" package="JUnit.Xml.TestLogger.NetCore.Tests.dll">
    <properties />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp" name="TestA" time="0.0000001">
      <failure type="failure" message="OneTimeSetUp: System.InvalidOperationException : Operation is not valid due to the current state of the object."></failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown" name="TestD" time="0.0021950" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown" name="TestC" time="0.0011090">
      <failure type="failure" message="TearDown : System.InvalidOperationException : Operation is not valid due to the current state of the object.">--TearDown
   at JUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown.TearDown() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 182</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup" name="TestB" time="0.0007420">
      <failure type="failure" message="System.InvalidOperationException : Operation is not valid due to the current state of the object.">at JUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup.SetUp() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 167</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture(&quot;Answer&quot;,42)" name="TestE" time="0.0000890" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture(&quot;Question&quot;,1)" name="TestE" time="0.0000280" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" name="TestData(1,&quot;A&quot;)" time="0.0116820" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" name="TestData(1,&quot;B&quot;)" time="0.0001490" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" name="TestData(2,&quot;A&quot;)" time="0.0205739">
      <failure type="failure" message="  failing for second case&#xD;&#xA;  Expected: not equal to 2&#xD;&#xA;  But was:  2&#xD;&#xA;">at JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 232</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" name="TestData(2,&quot;B&quot;)" time="0.0005820">
      <failure type="failure" message="  failing for second case&#xD;&#xA;  Expected: not equal to 2&#xD;&#xA;  But was:  2&#xD;&#xA;">at JUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 232</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture" name="InconclusiveTest" time="0.0007200" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture" name="SuccessTest" time="0.0000960" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.SuccessFixture" name="SuccessTest" time="0.0000830" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="FailTest11" time="0.0017970">
      <failure type="failure" message="  Expected: False&#xD;&#xA;  But was:  True&#xD;&#xA;">at JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.FailTest11() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 27</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="Ignored" time="0.0002950">
      <skipped />
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="Inconclusive" time="0.0005260" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="MultipleCategories" time="0.0001060" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="NoProperty" time="0.0001160" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="PassTest11" time="0.4068620" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="WithCategory" time="0.0002610" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="WithCategoryAndProperty" time="0.0001150" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="WithProperties" time="0.0001040" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" name="WithProperty" time="0.0000960" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" name="ExplicitTest" time="0.0000550" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" name="FailTest22" time="0.0009650">
      <failure type="failure" message="  Expected: False&#xD;&#xA;  But was:  True&#xD;&#xA;">at JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.FailTest22() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 94</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" name="IgnoredTest" time="0.0000110">
      <skipped />
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" name="Inconclusive" time="0.0004410" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" name="PassTest21" time="0.0003100" />
    <testcase classname="JUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" name="WarningTest" time="0.0003070">
      <skipped />
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.FailingOneTimeSetUp" name="TestA" time="0.0000001">
      <failure type="failure" message="OneTimeSetUp: System.InvalidOperationException : Operation is not valid due to the current state of the object."></failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.FailingOneTimeTearDown" name="TestD" time="0.0000820" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.FailingTearDown" name="TestC" time="0.0004980">
      <failure type="failure" message="TearDown : System.InvalidOperationException : Operation is not valid due to the current state of the object.">--TearDown
   at JUnit.Xml.TestLogger.Tests2.FailingTearDown.TearDown() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 137</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.FailingTestSetup" name="TestB" time="0.0004740">
      <failure type="failure" message="System.InvalidOperationException : Operation is not valid due to the current state of the object.">at JUnit.Xml.TestLogger.Tests2.FailingTestSetup.SetUp() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 122</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.ParametrizedFixture(&quot;Answer&quot;,42)" name="TestE" time="0.0001290" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.ParametrizedFixture(&quot;Question&quot;,1)" name="TestE" time="0.0000280" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.ParametrizedTestCases" name="TestData(1,&quot;A&quot;)" time="0.0002150" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.ParametrizedTestCases" name="TestData(1,&quot;B&quot;)" time="0.0000400" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.ParametrizedTestCases" name="TestData(2,&quot;A&quot;)" time="0.0005419">
      <failure type="failure" message="  failing for second case&#xD;&#xA;  Expected: not equal to 2&#xD;&#xA;  But was:  2&#xD;&#xA;">at JUnit.Xml.TestLogger.Tests2.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 187</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.ParametrizedTestCases" name="TestData(2,&quot;B&quot;)" time="0.0004890">
      <failure type="failure" message="  failing for second case&#xD;&#xA;  Expected: not equal to 2&#xD;&#xA;  But was:  2&#xD;&#xA;">at JUnit.Xml.TestLogger.Tests2.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 187</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.SuccessAndInconclusiveFixture" name="InconclusiveTest" time="0.0004310" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.SuccessAndInconclusiveFixture" name="SuccessTest" time="0.0000860" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.SuccessFixture" name="SuccessTest" time="0.0000810" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest1" name="FailTest11" time="0.0005720">
      <failure type="failure" message="  Expected: False&#xD;&#xA;  But was:  True&#xD;&#xA;">at JUnit.Xml.TestLogger.Tests2.UnitTest1.FailTest11() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 20</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest1" name="Ignored" time="0.0000110">
      <skipped />
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest1" name="Inconclusive" time="0.0004320" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest1" name="PassTest11" time="0.4104580" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest2" name="ExplicitTest" time="0.0000410" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest2" name="FailTest22" time="0.0035250">
      <failure type="failure" message="  Expected: False&#xD;&#xA;  But was:  True&#xD;&#xA;">at JUnit.Xml.TestLogger.Tests2.UnitTest2.FailTest22() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 49</failure>
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest2" name="IgnoredTest" time="0.0000310">
      <skipped />
    </testcase>
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest2" name="Inconclusive" time="0.0009130" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest2" name="PassTest21" time="0.0005760" />
    <testcase classname="JUnit.Xml.TestLogger.Tests2.UnitTest2" name="WarningTest" time="0.0006100">
      <skipped />
    </testcase>
    <system-out>{EEEE1DA6-6296-4486-BDA5-A50A19672F0F}
{C33FF4B5-75E1-4882-B968-DF9608BFE7C2}

{2010CAE3-7BC0-4841-A5A3-7D5F947BB9FB}
{998AC9EC-7429-42CD-AD55-72037E7AF3D8}


Test Framework Informational Messages:
NUnit Adapter 3.10.0.21: Test execution started
Running all tests in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\bin\Debug\netcoreapp3.1\JUnit.Xml.TestLogger.NetCore.Tests.dll
NUnit3TestExecutor converted 52 of 52 NUnit test cases
NUnit Adapter 3.10.0.21: Test execution complete
</system-out>
    <system-err>Warning - SetUp failed for test fixture JUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp
Warning - System.InvalidOperationException : Operation is not valid due to the current state of the object.
Warning -    at JUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp.OneTimeSetUp() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 152
Warning - TearDown failed for test fixture JUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown
Warning - TearDown : System.InvalidOperationException : Operation is not valid due to the current state of the object.
Warning - --TearDown
   at JUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown.OneTimeTearDown() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 197
Warning - {D46DFA10-EEDD-49E5-804D-FE43051331A7}
Warning - {33F5FD22-6F40-499D-98E4-481D87FAEAA1}
Warning - SetUp failed for test fixture JUnit.Xml.TestLogger.Tests2.FailingOneTimeSetUp
Warning - System.InvalidOperationException : Operation is not valid due to the current state of the object.
Warning -    at JUnit.Xml.TestLogger.Tests2.FailingOneTimeSetUp.OneTimeSetUp() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 107
Warning - TearDown failed for test fixture JUnit.Xml.TestLogger.Tests2.FailingOneTimeTearDown
Warning - TearDown : System.InvalidOperationException : Operation is not valid due to the current state of the object.
Warning - --TearDown
   at JUnit.Xml.TestLogger.Tests2.FailingOneTimeTearDown.OneTimeTearDown() in C:\Users\REDACTED\Documents\GitHub\junit.testlogger\test\assets\JUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 152
</system-err>
  </testsuite>
</testsuites>